const Menus=[
   {
     title:'首页',
     path:'/home'
   },
   {
     title:'数据统计',
     path:'/home/data'
   },
   {
     title:'用户管理',
     path:'/home/user',
     children:[
       {
         title:'商品列表',
         path:'/home/goods/list'
       },
       {
         title:'商品添加',
         path:'/home/goods/add'
       },
       {
         title:'商品修改',
         path:'/home/goods/update',
         children:[
           {
             title:'三级测试1',
             path:'/home/goods/update/test1'
           },
           {
             title:'三级测试2',
             path:'/home/goods/update/test2'
           },
         ]
       },
     ]
   },
   {
     title:"商品管理",
     path:'/home/goods',
     children:[
       {
         title:'商品列表',
         path:'/home/goods/list'
       },
       {
        title:'未知元素',
        path:'/home/goods/xxx'
      },
     ]
   }
 ]

 export default Menus